name: Publish latest version

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sanitize metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: latest
          images: git.mylloon.fr/${{ github.repository }}

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ github.server_url }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
